apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pab5c36dk-nodejs
  janus-idp.io/tekton: pab5c36dk-nodejs
  backstage.io/kubernetes-id: pab5c36dk-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pab5c36dk-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
